version: "3"
services:
  app:
    build: .
    image: video-club-rest:1.0
    ports:
      - 3000:3000
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "secret"
